services:
  - type: cron
    name: frontend-job-scraper
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    schedule: "0 */4 * * *" # Every 4 hours
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_HOST
        fromService:
          type: secret
          name: email-host
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        fromService:
          type: secret
          name: email-user
      - key: EMAIL_PASS
        fromService:
          type: secret
          name: email-pass
      - key: EMAIL_TO
        fromService:
          type: secret
          name: email-to
      - key: SCRAPING_DELAY
        value: "3000"
      - key: MAX_PAGES_PER_SITE
        value: "3"
      - key: USER_AGENT
        value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      - key: CRON_SCHEDULE
        value: "0 */4 * * *"
